common_args:
  device: 'gpu'
  device_num:
    - 1
  device_name: 'cuda:1'

data_args:
  dataset: "CIFAR10"
  num_classes: 10
  data_cache_dir: "/srv/data/image_dataset/CIFAR10"

model_args:
  architecture: "Vggsmall"
  snet: true
  model_name: "Vggsmall_BC"
  model_cache_dir: "./trained_model/vgg/cifar10"
  expansion: 1
  forward_type: "snet_test_fine_tune"

training_args:
  project_name: "Vggsmall"
  use_wandb: true
  early_stopping: false
  epochs: 400
  num_workers: 1
  batch_size: 1000
  save_top_k: 5
  learning_rate: 0.02
  momentum: 0.9
  weight_decay: 0.005
  pos_weight: 396
  milestones:
    - 100
    - 150
    - 300

exit_strategy:
  ckpt_path: './trained_model/vgg/cifar10/Vggsmall_BC.ckpt'
  strategy_name: "LargeN"
  activation: "sigmoid"
  num_exit_points: 6

search:
  search: true
  start_thresh: 0.01
  step: 0.01
  tolerance: 0.001