common_args:
  device: 'gpu'
  device_num:
    - 2
  device_name: 'cuda:2'

data_args:
  dataset: "CIFAR10_224"
  num_classes: 10
  data_cache_dir: "/srv/data/image_dataset/CIFAR10"

model_args:
  architecture: "Alexnet"
  snet: true
  model_name: "alex_BCn"
  model_cache_dir: "./trained_model/alex"
  expansion: 1
  forward_type: "snet_train"

training_args:
  project_name: "Alexnet"
  pretrained_path: "/home/wang/code/project1/trained_model/Alexnet/checkpoint.pth"
  use_wandb: true
  early_stopping: false
  patience: 50
  min_delta: 0.0001
  epochs: 50
  num_workers: 1
  batch_size: 100
  save_top_k: 5
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.
  pos_weight: 36


exit_strategy:
  strategy_name: "LargeN"
  activation: "sigmoid"
  num_exit_points: 5


















