common_args:
  device: 'gpu'
  device_num:
    - 0
  device_name: 'cuda:0'

data_args:
  dataset: "CIFAR100"
  num_classes: 100
  data_cache_dir: "/srv/data/image_dataset/CIFAR100"

model_args:
  architecture: "Vggsmall"
  snet: false
  model_name: "Vggsmall_prune"
  model_cache_dir: "./trained_model/vgg/prune"
  expansion: 2
  forward_type: "snet_train"

training_args:
  project_name: "Vggsmall_prune"
  use_wandb: true
  early_stopping: false
  epochs: 1000
  num_workers: 4
  batch_size: 100
  save_top_k: 5
  learning_rate: 0.001
  momentum: 0.9
  pos_weight: 396
  weight_decay: 0.0005
  milestones:
    - 500
  gamma: 0.1

exit_strategy:
  ckpt_path: 'trained_model/vgg/Vggsmall-v5.ckpt'
  strategy_name: "LargeN"
  activation: "sigmoid"
  num_exit_points: 6


















