common_args:
  device: 'gpu'
  device_num:
    - 0
  device_name: 'cuda:0'

data_args:
  dataset: "CIFAR100"
  num_classes: 100
  data_cache_dir: "/srv/data/image_dataset/CIFAR100"

model_args:
  architecture: "Vggsmall"
  snet: true
  model_name: "Vggsmall_bc_prune"
  model_cache_dir: "./trained_model/vgg/prune"
  expansion: 2
  forward_type: "snet_test_mac"

training_args:
  project_name: "Vggsmall_prune"
  use_wandb: false
  early_stopping: false
  epochs: 1000
  num_workers: 1
  batch_size: 1
  save_top_k: 5
  learning_rate: 0.001
  momentum: 0.9
  pos_weight: 396
  weight_decay: 0.0005
  milestones:
    - 500
  gamma: 0.1

exit_strategy:
  ckpt_path: './trained_model/vgg/prune/Vggsmall_bc_prune0.1.ckpt'
  strategy_name: "LargeN"
  activation: "sigmoid"
  num_exit_points: 6

search:
  search: true
  start_thresh: 0.01
  step: 0.01
  tolerance: 0.008
